# Generated by Django 2.0.4 on 2018-04-14 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_models', '0002_auto_20180409_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='twitter_models.Account'),
            preserve_default=False,
        ),
    ]
