# Generated by Django 2.0.4 on 2018-04-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_models', '0003_datafile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='account',
        ),
        migrations.AddField(
            model_name='estimate',
            name='model_class',
            field=models.CharField(default='hawkes', max_length=100),
            preserve_default=False,
        ),
    ]
