# Generated by Django 2.0.4 on 2018-04-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_models', '0007_account_bins'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='marketUrl',
            field=models.TextField(default='https://predictit.com'),
            preserve_default=False,
        ),
    ]
