# Generated by Django 2.0.4 on 2018-04-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_models', '0008_account_marketurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='marketUrl',
            new_name='market_url',
        ),
    ]
